### ISSUE TITLE
[BUG] Instantiating `Merge` class fails

### ISSUE THREAD

**Issue by roeap** [memgraph/gqlalchemy#117]
**Describe the bug** 

In the line below, `MergePartialQuery` is invoked with `optional` argument, but class constructor does not accept arguments.

https://github.com/memgraph/gqlalchemy/blob/824b777f9fe58f318740085b1320061c1a6fa225/gqlalchemy/query_builder.py#L607

**To Reproduce** Steps to reproduce the behavior:

```py
from gqlalchemy import merge

merge()
```

**Expected behavior** 

no exception when instantiating class :)

**Comment by g-despot** [comment]
Thank you for reporting this. The bug is fixed in version [1.1.5](https://pypi.org/project/gqlalchemy/1.1.5/).
