### ISSUE TITLE
Rename edge_label to edge_type

### ISSUE THREAD

**Issue by katarinasupe** [memgraph/gqlalchemy#123]
I noticed that `to()` method in query builder has argument `edge_label` for relationship type. 
```
 def to(
        self,
        edge_label: Optional[str] = "",
        directed: Optional[bool] = True,
        variable: Optional[str] = None,
        relationship: Optional["Relationship"] = None,
        **kwargs,
    ) -> "DeclarativeBase":
```

I know there was a discussion because whether to name it `type`. Type is not a reserved keyword in Python, but it is still not wise to use it. Hence, I would suggest `edge_type`.

**Edit**:
When I think about it more, it should be named `relationship` or `relationship_type`, since we are not using `edge` in our codebase.

**Comment by brunos252** [comment]
relationship_type vote!

**Comment by g-despot** [comment]
I also think that `relationship_type` is the most descriptive and correct naming.

**Comment by brunos252** [comment]
While to() uses a variable `type_str` in:
`type_str = to_cypher_labels(edge_label)`
from_() uses `labels_str` for the same code, so this should be fixed along with other changes.

Also, `EdgePartialQuery` has a parameter called `labels` (Probably because `NodePartialQuery` has the same parameters).
