### ISSUE TITLE
No support for setting node (or relationship) property to a variable value

### ISSUE THREAD

**Issue by brunos252** [memgraph/gqlalchemy#137]
**Describe the bug**
In the Cypher grammar, node and relationship properties are defined as:
mapLiteral : '{' ( propertyKeyName ':' expression ( ',' propertyKeyName ':' expression )* )? '}' ;
where the expression can be a variable, but we do not have this support.
Because of this, it is not possible to make this partial query:
`CREATE (n {prop: var})`, where `var` is a variable.
To make it, we would write something like:
`.create().node(variable="n", prop="var")` and `var` would be passed as a string; `prop: "var"`

This is particularly necessary for FOREACH clause, for instance:
`FOREACH ( i IN [1, 2, 3] | CREATE (n {id: i}) )`

**Comment by katarinasupe** [comment]
@BorisTasevski and @g-despot let's discuss this here sometime soon so that Bruno knows what is best to do next 😄

**Comment by Josipmrden** [comment]
Maybe to introduce a new class inside the QueryBuilder logic, for example Property
which will be utilized like this: https://pypika.readthedocs.io/en/latest/2_tutorial.html#tables-columns-schemas-and-databases

```
def to_cypher_value(value: Any, config: NetworkXCypherConfig = None) -> str:
    """Converts value to a valid Cypher type."""
    if config is None:
        config = NetworkXCypherConfig()

    value_type = type(value)

    if value_type == str and value.lower() == "null":
        return value
   **if isinstance(value, Property): return str(value)** -> makes Property would just have an initializer with its value

    if value_type == float and math.isnan(value):
        if config.nan_handler == NanValuesHandle.THROW_EXCEPTION:
            raise NanException("Nan values are not allowed!")

        return "null"

    if value_type in [int, float, bool]:
        return str(value)

    if value_type in [list, set, tuple]:
        return f"[{', '.join(map(to_cypher_value, value))}]"

    if value_type == dict:
        lines = ", ".join(f"{k}: {to_cypher_value(v)}" for k, v in value.items())
        return f"{{{lines}}}"

    if value is None:
        return "null"

    if value.lower() in ["true", "false"]:
        return value

    return f"'{value}'"
```

Which would eliminate all our needs to have "is_variable" in FOREACH, WHERE, NODE, and other clauses. Not to mention we'll have to change it at all these methods if by some chance a lightbulb hits us with a better implementation
