### ISSUE TITLE
Indexes only work if NetworkX ids are integers

### ISSUE THREAD

**Issue by gitbuda** [memgraph/gqlalchemy#14]
`_create_node` and `_create_edge` accept only integers as ids (`nx_id`, `from_id`, `to_id`). The ids could be, e.g., strings. Graphviz Python libraries create node ids that are integers. If ids are not integers it's impossible to generate valid Memgraph queries.

Take a look [here](https://youtu.be/WSUP_-2rA6g?t=3955) (**How to analyze Python, Cpp and Rust dependencies? PART 2**) to see the details about the problem. The solution was to use `gqlalchemy` as a library and reuse some of the functions, but it's definitely possible to push all the required capabilities into `gqlalchemy`.

**Comment by MasterMedo** [comment]
I see two ways to tackle this.

1. Add support for strings and escape the index when creating the cypher query with quotes.
2. Support all data types by hashing the ID with a function to an integer.

What do you think, is there a better way for approaching this?

**Comment by gitbuda** [comment]
Both options should be fine :smile: Option 1. seems a bit better to me because the same values are used directly (all types could be supported).

**Comment by MasterMedo** [comment]
Yeah, I agree for strings, but what do you mean by "all types could be supported"? How would you support IDs of type "Person", for example? By using the hash approach that would be trivial.

Maybe we could support built-in types by escaping them so the representation stays the same, but if the type is unknown we could use the python built-in "id" function to get the id.

**Comment by jbajic** [comment]
Thanks for reporting the issue, I agree with option one, this was overlooked in the initial implementation...

**Comment by gitbuda** [comment]
Here is a minimal example, `example.py` produces queries that can't be imported. Please rename the example files because `.py` and `.dot` can't be directly uploaded here :smile:

[example_dot.txt](https://github.com/memgraph/gqlalchemy/files/7006429/example_dot.txt)
[example_py.txt](https://github.com/memgraph/gqlalchemy/files/7006430/example_py.txt)
[requirements.txt](https://github.com/memgraph/gqlalchemy/files/7006426/requirements.txt)
