### ISSUE TITLE
[BUG] can't be installed on Python 3.11 due to dependency on pyarrow

### ISSUE THREAD

**Issue by smithbp** [memgraph/gqlalchemy#203]
**Memgraph version** Which version did you use?
Using the docker image for memgraph: "memgraph/memgraph-platform"

**Environment** Some information about the environment you are using Memgraph
on: operating system, how do you connect, with or without docker, which driver
etc.
Using docker for memgraph, and using poetry to install gqlalchemy. This is done on a pyenv 3.11 virtual environment in MacOS.

**Describe the bug** A clear and concise description of what the bug is.
pyarrow is not yet compatible with Python 3.11. Therefore it can't be installed, and breaks gqlalchemy.

**To Reproduce** Steps to reproduce the behavior:

1. create a pyenv virtualenv 3.11 and activate
2. Create a poetry project
3. Run 'poetry add gqlalchemy'
4.  Run poetry install

**Expected behavior** A clear and concise description of what you expected to
happen.
The poetry installation should fail due to a failure to install pyarrow

**Logs** If applicable, add logs of Memgraph, CLI output or screenshots to help
explain your problem.

 • Installing pyarrow (9.0.0): Failed

  CalledProcessError

  Command '['/Users/brandon/.pyenv/versions/3.11.0/envs/fulcrum-maps-test/bin/python', '-m', 'pip', 'install', '--use-pep517', '--disable-pip-version-check', '--prefix', '/Users/brandon/.pyenv/versions/3.11.0/envs/fulcrum-maps-test', '--no-deps', '/Users/brandon/Library/Caches/pypoetry/artifacts/b8/98/15/cf9a801ac46e67488b2720c005c9e5f3756a53f12868504fb202083132/pyarrow-9.0.0.tar.gz']' returned non-zero exit status 1.

  at ~/.pyenv/versions/3.10.7/lib/python3.10/subprocess.py:524 in run
       520│             # We don't call process.wait() as .__exit__ does that for us.
       521│             raise
       522│         retcode = process.poll()
       523│         if check and retcode:
    →  524│             raise CalledProcessError(retcode, process.args,
       525│                                      output=stdout, stderr=stderr)
       526│     return CompletedProcess(process.args, retcode, stdout, stderr)
       527│
       528│

The following error occurred when trying to handle this error:

  EnvCommandError

  Command ['/Users/brandon/.pyenv/versions/3.11.0/envs/fulcrum-maps-test/bin/python', '-m', 'pip', 'install', '--use-pep517', '--disable-pip-version-check', '--prefix', '/Users/brandon/.pyenv/versions/3.11.0/envs/fulcrum-maps-test', '--no-deps', '/Users/brandon/Library/Caches/pypoetry/artifacts/b8/98/15/cf9a801ac46e67488b2720c005c9e5f3756a53f12868504fb202083132/pyarrow-9.0.0.tar.gz'] errored with the following return code 1, and output:
  Looking in indexes: https://brandon.smith%40firstmode.com:****@firstmode.jfrog.io/artifactory/api/pypi/fulcrum-pypi/simple
  Processing /Users/brandon/Library/Caches/pypoetry/artifacts/b8/98/15/cf9a801ac46e67488b2720c005c9e5f3756a53f12868504fb202083132/pyarrow-9.0.0.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
    Preparing metadata (pyproject.toml): started
    Preparing metadata (pyproject.toml): finished with status 'done'
  Building wheels for collected packages: pyarrow
    Building wheel for pyarrow (pyproject.toml): started
    Building wheel for pyarrow (pyproject.toml): finished with status 'error'
    error: subprocess-exited-with-error

    × Building wheel for pyarrow (pyproject.toml) did not run successfully.
    │ exit code: 1
    ╰─> [258 lines of output]
        running bdist_wheel
        running build
        running build_py
        creating build
        creating build/lib.macosx-12.6-arm64-cpython-311
        creating build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/orc.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/conftest.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/_generated_version.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/benchmark.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/_compute_docstrings.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/ipc.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/util.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/flight.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/cffi.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/substrait.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/filesystem.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/__init__.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/plasma.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/types.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/dataset.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/cuda.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/feather.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/pandas_compat.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/fs.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/csv.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/jvm.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/hdfs.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/json.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/serialization.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/compute.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        creating build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/test_tensor.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/test_ipc.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/conftest.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/test_convert_builtin.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/test_misc.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/arrow_16597.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/test_gandiva.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/strategies.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/test_adhoc_memory_leak.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/arrow_7980.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/util.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/test_orc.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/test_table.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/test_array.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/test_deprecations.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/test_serialization_deprecated.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/__init__.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/test_io.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/test_util.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/test_cuda_numba_interop.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/test_cffi.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/test_schema.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/test_jvm.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/test_plasma_tf_op.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/test_fs.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/test_udf.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/test_filesystem.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/pandas_threaded_import.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/pandas_examples.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/test_cython.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/test_sparse_tensor.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/test_dataset.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/test_builder.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/test_cuda.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/test_extension_type.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/test_feather.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/test_pandas.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/test_memory.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/test_exec_plan.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/test_flight.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/read_record_batch.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/test_json.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/test_serialization.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/test_compute.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/test_hdfs.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/deserialize_buffer.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/test_strategies.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/test_csv.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/test_plasma.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/test_scalars.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/test_gdb.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/test_types.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/test_substrait.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        creating build/lib.macosx-12.6-arm64-cpython-311/pyarrow/vendored
        copying pyarrow/vendored/version.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/vendored
        copying pyarrow/vendored/__init__.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/vendored
        copying pyarrow/vendored/docscrape.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/vendored
        creating build/lib.macosx-12.6-arm64-cpython-311/pyarrow/parquet
        copying pyarrow/parquet/encryption.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/parquet
        copying pyarrow/parquet/__init__.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/parquet
        creating build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests/parquet
        copying pyarrow/tests/parquet/test_basic.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests/parquet
        copying pyarrow/tests/parquet/conftest.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests/parquet
        copying pyarrow/tests/parquet/encryption.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests/parquet
        copying pyarrow/tests/parquet/test_parquet_writer.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests/parquet
        copying pyarrow/tests/parquet/test_metadata.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests/parquet
        copying pyarrow/tests/parquet/__init__.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests/parquet
        copying pyarrow/tests/parquet/test_datetime.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests/parquet
        copying pyarrow/tests/parquet/common.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests/parquet
        copying pyarrow/tests/parquet/test_dataset.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests/parquet
        copying pyarrow/tests/parquet/test_data_types.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests/parquet
        copying pyarrow/tests/parquet/test_pandas.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests/parquet
        copying pyarrow/tests/parquet/test_parquet_file.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests/parquet
        copying pyarrow/tests/parquet/test_compliant_nested_type.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests/parquet
        copying pyarrow/tests/parquet/test_encryption.py -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests/parquet
        running egg_info
        writing pyarrow.egg-info/PKG-INFO
        writing dependency_links to pyarrow.egg-info/dependency_links.txt
        writing entry points to pyarrow.egg-info/entry_points.txt
        writing requirements to pyarrow.egg-info/requires.txt
        writing top-level names to pyarrow.egg-info/top_level.txt
        listing git files failed - pretending there aren't any
        reading manifest file 'pyarrow.egg-info/SOURCES.txt'
        reading manifest template 'MANIFEST.in'
        warning: no files found matching '../LICENSE.txt'
        warning: no files found matching '../NOTICE.txt'
        warning: no previously-included files matching '*.so' found anywhere in distribution
        warning: no previously-included files matching '*.pyc' found anywhere in distribution
        warning: no previously-included files matching '*~' found anywhere in distribution
        warning: no previously-included files matching '#*' found anywhere in distribution
        warning: no previously-included files matching '.git*' found anywhere in distribution
        warning: no previously-included files matching '.DS_Store' found anywhere in distribution
        no previously-included directories found matching '.asv'
        writing manifest file 'pyarrow.egg-info/SOURCES.txt'
        copying pyarrow/__init__.pxd -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/_compute.pxd -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/_compute.pyx -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/_csv.pxd -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/_csv.pyx -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/_cuda.pxd -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/_cuda.pyx -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/_dataset.pxd -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/_dataset.pyx -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/_dataset_orc.pyx -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/_dataset_parquet.pyx -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/_exec_plan.pyx -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/_feather.pyx -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/_flight.pyx -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/_fs.pxd -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/_fs.pyx -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/_gcsfs.pyx -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/_hdfs.pyx -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/_hdfsio.pyx -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/_json.pyx -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/_orc.pxd -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/_orc.pyx -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/_parquet.pxd -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/_parquet.pyx -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/_parquet_encryption.pxd -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/_parquet_encryption.pyx -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/_plasma.pyx -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/_s3fs.pyx -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/_substrait.pyx -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/array.pxi -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/benchmark.pxi -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/builder.pxi -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/compat.pxi -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/config.pxi -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/error.pxi -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/gandiva.pyx -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/io.pxi -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/ipc.pxi -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/lib.pxd -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/lib.pyx -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/memory.pxi -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/pandas-shim.pxi -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/public-api.pxi -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/scalar.pxi -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/serialization.pxi -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/table.pxi -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/tensor.pxi -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        copying pyarrow/types.pxi -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow
        creating build/lib.macosx-12.6-arm64-cpython-311/pyarrow/includes
        copying pyarrow/includes/common.pxd -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/includes
        copying pyarrow/includes/libarrow_feather.pxd -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/includes
        copying pyarrow/includes/__init__.pxd -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/includes
        copying pyarrow/includes/libgandiva.pxd -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/includes
        copying pyarrow/includes/libarrow_python.pxd -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/includes
        copying pyarrow/includes/libarrow_flight.pxd -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/includes
        copying pyarrow/includes/libarrow_dataset_parquet.pxd -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/includes
        copying pyarrow/includes/libarrow_dataset.pxd -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/includes
        copying pyarrow/includes/libarrow_substrait.pxd -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/includes
        copying pyarrow/includes/libarrow.pxd -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/includes
        copying pyarrow/includes/libarrow_cuda.pxd -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/includes
        copying pyarrow/includes/libarrow_fs.pxd -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/includes
        copying pyarrow/includes/libplasma.pxd -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/includes
        copying pyarrow/tests/bound_function_visit_strings.pyx -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        copying pyarrow/tests/pyarrow_cython_example.pyx -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests
        creating build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tensorflow
        copying pyarrow/tensorflow/plasma_op.cc -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tensorflow
        creating build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests/data
        creating build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests/data/feather
        copying pyarrow/tests/data/feather/v0.17.0.version.2-compression.lz4.feather -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests/data/feather
        creating build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests/data/orc
        copying pyarrow/tests/data/orc/README.md -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests/data/orc
        copying pyarrow/tests/data/orc/TestOrcFile.emptyFile.jsn.gz -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests/data/orc
        copying pyarrow/tests/data/orc/TestOrcFile.emptyFile.orc -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests/data/orc
        copying pyarrow/tests/data/orc/TestOrcFile.test1.jsn.gz -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests/data/orc
        copying pyarrow/tests/data/orc/TestOrcFile.test1.orc -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests/data/orc
        copying pyarrow/tests/data/orc/TestOrcFile.testDate1900.jsn.gz -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests/data/orc
        copying pyarrow/tests/data/orc/TestOrcFile.testDate1900.orc -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests/data/orc
        copying pyarrow/tests/data/orc/decimal.jsn.gz -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests/data/orc
        copying pyarrow/tests/data/orc/decimal.orc -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests/data/orc
        creating build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests/data/parquet
        copying pyarrow/tests/data/parquet/v0.7.1.all-named-index.parquet -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests/data/parquet
        copying pyarrow/tests/data/parquet/v0.7.1.column-metadata-handling.parquet -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests/data/parquet
        copying pyarrow/tests/data/parquet/v0.7.1.parquet -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests/data/parquet
        copying pyarrow/tests/data/parquet/v0.7.1.some-named-index.parquet -> build/lib.macosx-12.6-arm64-cpython-311/pyarrow/tests/data/parquet
        running build_ext
        creating /private/var/folders/x_/mctxkbfj2wx673tc_r7fy0pc0000gp/T/pip-req-build-9n4wvrvp/build/temp.macosx-12.6-arm64-cpython-311
        -- Running cmake for pyarrow
        cmake -DPYTHON_EXECUTABLE=/Users/brandon/.pyenv/versions/3.11.0/envs/fulcrum-maps-test/bin/python -DPython3_EXECUTABLE=/Users/brandon/.pyenv/versions/3.11.0/envs/fulcrum-maps-test/bin/python "" -DPYARROW_BUILD_CUDA=off -DPYARROW_BUILD_SUBSTRAIT=off -DPYARROW_BUILD_FLIGHT=off -DPYARROW_BUILD_GANDIVA=off -DPYARROW_BUILD_DATASET=off -DPYARROW_BUILD_ORC=off -DPYARROW_BUILD_PARQUET=off -DPYARROW_BUILD_PARQUET_ENCRYPTION=off -DPYARROW_BUILD_PLASMA=off -DPYARROW_BUILD_GCS=off -DPYARROW_BUILD_S3=off -DPYARROW_BUILD_HDFS=off -DPYARROW_USE_TENSORFLOW=off -DPYARROW_BUNDLE_ARROW_CPP=off -DPYARROW_BUNDLE_BOOST=off -DPYARROW_GENERATE_COVERAGE=off -DPYARROW_BOOST_USE_SHARED=on -DPYARROW_PARQUET_USE_SHARED=on -DCMAKE_BUILD_TYPE=release /private/var/folders/x_/mctxkbfj2wx673tc_r7fy0pc0000gp/T/pip-req-build-9n4wvrvp
        CMake Warning:
          Ignoring empty string ("") provided on the command line.

        -- The C compiler identification is AppleClang 14.0.0.14000029
        -- The CXX compiler identification is AppleClang 14.0.0.14000029
        -- Detecting C compiler ABI info
        -- Detecting C compiler ABI info - done
        -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
        -- Detecting C compile features
        -- Detecting C compile features - done
        -- Detecting CXX compiler ABI info
        -- Detecting CXX compiler ABI info - done
        -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
        -- Detecting CXX compile features
        -- Detecting CXX compile features - done
        -- System processor: arm64
        -- Performing Test CXX_SUPPORTS_ARMV8_ARCH
        -- Performing Test CXX_SUPPORTS_ARMV8_ARCH - Success
        -- Arrow build warning level: PRODUCTION
        -- Configured for RELEASE build (set with cmake -DCMAKE_BUILD_TYPE={release,debug,...})
        -- Build Type: RELEASE
        -- Generator: Unix Makefiles
        -- Build output directory: /private/var/folders/x_/mctxkbfj2wx673tc_r7fy0pc0000gp/T/pip-req-build-9n4wvrvp/build/temp.macosx-12.6-arm64-cpython-311/release
        -- Found Python3: /Users/brandon/.pyenv/versions/3.11.0/envs/fulcrum-maps-test/bin/python (found version "3.11.0") found components: Interpreter Development.Module NumPy
        -- Found Python3Alt: /Users/brandon/.pyenv/versions/3.11.0/envs/fulcrum-maps-test/bin/python
        -- Found PkgConfig: /opt/homebrew/bin/pkg-config (found version "0.29.2")
        -- Could NOT find Arrow (missing: Arrow_DIR)
        -- Checking for module 'arrow'
        --   No package 'arrow' found
        CMake Error at /opt/homebrew/Cellar/cmake/3.23.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
          Could NOT find Arrow (missing: ARROW_INCLUDE_DIR ARROW_LIB_DIR
          ARROW_FULL_SO_VERSION ARROW_SO_VERSION)
        Call Stack (most recent call first):
          /opt/homebrew/Cellar/cmake/3.23.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
          cmake_modules/FindArrow.cmake:450 (find_package_handle_standard_args)
          cmake_modules/FindArrowPython.cmake:46 (find_package)
          CMakeLists.txt:236 (find_package)

        -- Configuring incomplete, errors occurred!
        See also "/private/var/folders/x_/mctxkbfj2wx673tc_r7fy0pc0000gp/T/pip-req-build-9n4wvrvp/build/temp.macosx-12.6-arm64-cpython-311/CMakeFiles/CMakeOutput.log".
        See also "/private/var/folders/x_/mctxkbfj2wx673tc_r7fy0pc0000gp/T/pip-req-build-9n4wvrvp/build/temp.macosx-12.6-arm64-cpython-311/CMakeFiles/CMakeError.log".
        error: command '/opt/homebrew/bin/cmake' failed with exit code 1
        [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
    ERROR: Failed building wheel for pyarrow
  Failed to build pyarrow
  ERROR: Could not build wheels for pyarrow, which is required to install pyproject.toml-based projects

**Additional context** Add any other context about the problem here.

**Comment by smithbp** [comment]
@BorisTasevski I tried to create a branch/PR, but I have no push permissions to this repo. The change is super simple if someone on the project wants to make it.

line 40 in pyproject.toml --> pyarrow = "^10.0.0"

This will also require an update to the poetry.lock file: 
* Remove the poetry.lock file
*  reinstall poetry on a fresh python environment

**Comment by BorisTasevski** [comment]
Hi @smithbp , 

thank You for Your contribution, 

we will most likely start supporting new python version with the next release of gqlalchemy.

**Comment by Josipmrden** [comment]
Put this task in the backlog.

**Comment by kapilt** [comment]
Pyarrow supports python 3.11, this is due to using an old version in the poetry dependency specification. Maybe try just updating the dependencies in gqlalchemy.

**Comment by barosch47** [comment]
Hi, are there any updates on this ? 
Python 3.11 and Pydantic V2 (see:  [Issue 257](https://github.com/memgraph/gqlalchemy/issues/257) ) would be very valuable.

**Comment by katarinasupe** [comment]
Hi @barosch47, we still need to plan for the next release, and it will be appropriately updated on GitHub. Is this a blocking issue for you? It would help me understand the urgency. P.S. we are always open to outside contributions :)

**Comment by jngarber-st** [comment]
Python 3.11 support would be very good. 3 dependencies (networkX, numpy, pyarrow) have been mentioned in issues as not being compatible with python 3.11. Each of those dependencies currently work with python 3.11. Maybe there are more dependencies with remaining issues?

**Comment by mckij** [comment]
Is there any way that this issue's priority can be bumped up?  

I want to use gqlalchemy for a Python 3.11 project and no support for the latest python version is a deal breaker for me and I would assume many other potential users.

**Comment by mckij** [comment]
> Hi @mckij, we will discuss priorities on GQLAlchemy next week, and I will keep you posted here. I was just wondering, is this a deal breaker for you using Memgraph or only GQLAlchemy as a client?

I was planning on using the GQLAlchemy client to talk to a Neo4j database.  Unfortunately my existing code base is all on Python 3.11 which means GQLAlchemy is currently not an option for me.

**Comment by katarinasupe** [comment]
Thank you, both @smithbp and @mckij, for your input. I will get back to you as soon as we discuss this.

**Comment by katarinasupe** [comment]
Hi @smithbp @kapilt @barosch47 @jngarber-st @mckij and thank you for leaving your comments on this issue. We do appreciate it a lot and we decided to work on the release at the end of the next week. Stay tuned :)
