### ISSUE TITLE
Upgrade to pydantic v2

### ISSUE THREAD

**Issue by apowers313** [memgraph/gqlalchemy#257]
Pydantic released a v2 in June 2023. I'd prefer to use the newer [APIs](https://docs.pydantic.dev/latest/migration/), but gqlalchemy uses v1 which is a dependency conflict.

Any plans for gqlalchemy to upgrade to pydantic v2?

**Comment by katarinasupe** [comment]
Hi @apowers313, thank you for reporting this. We did not have such plans, but I will add this issue to Milestone 1.5 to potentially include it there. Is that a blocker for you, or just nice to have?

**Comment by alex-linx** [comment]
@katarinasupe 
Hi, we are also looking forward to migrating our codebase to pydantic V2, because of all the new features and improvements. But we are waiting for all the other libs we use to do the transition as well.
Do you have maybe a timeframe for this?

**Comment by apowers313** [comment]
FYI, it seems like the easiest upgrade path might be to upgrade to Pydantic v2 and then [import the v1 APIs](https://docs.pydantic.dev/latest/migration/#continue-using-pydantic-v1-features) as mentioned in the migration guide.

**Comment by antejavor** [comment]
Hi, @apowers313 and @alex-linx, @katarinasupe is currently on AL, but once she returns next week, we will get back to you on this issue.

**Comment by rahulvramesh** [comment]
hi, we are having same issue. even for simple connection it throws error

**Comment by apowers313** [comment]
I would recommend downgrading to pydantic v1 (e.g. `pip install "pydantic>=1.0.0"`) or using [pymgclient](https://github.com/memgraph/pymgclient) as a work around.

**Comment by rahulvramesh** [comment]
thanks @apowers313 pymg directly

**Comment by chrisgoddard** [comment]
+1 for me on v2 support - as @apowers313 noted you can use v2 and import the v1 apis to make the migration simpler

**Comment by rahulvramesh** [comment]
does changing the import with v1. will work ?

**Comment by katarinasupe** [comment]
@apowers313 @alex-linx @rahulvramesh @chrisgoddard thank you for jumping in on this issue. We will work on the release at the end of the next week and try to include this dependency bump. Stay tuned :)
