### ISSUE TITLE
Missing documentation section on execute() 

### ISSUE THREAD

**Issue by antejavor** [memgraph/gqlalchemy#289]
`execute` and `execute__and_fetch` are not in the docs: https://github.com/memgraph/gqlalchemy/blob/main/gqlalchemy/connection.py#L48 

We should document this.

**Comment by katarinasupe** [comment]
This was updated with the last release (reference guide regenerated)

**Comment by siddharth-gitrepo** [comment]
Can anyone pls share the document link.

**Comment by katarinasupe** [comment]
Hi @siddharth-gitrepo, this is what we were referring to: https://memgraph.github.io/gqlalchemy/reference/gqlalchemy/connection/#execute

**Comment by siddharth-gitrepo** [comment]
Thanks ! 
well i am trying to load OSM (open street map) data consisting of nodes, edges into memgraph. The data for Delhi city is about 300,000 nodes and 600,000 edges. 
Later i plan to run shortest path computation on the graph. However, the computation consists of about 170,000 shortest path computations with start and end nodes within a kilometre range. I am trying to devise a method to load data in short amount of time and run computation on different set of start and end nodes.

**Comment by katarinasupe** [comment]
That sounds like a cool project @siddharth-gitrepo. If you still haven't, join our [Discord community](https://discord.gg/memgraph) where we talk all Memgraph-related every day. There you can ask questions and get help if needed. For more hands-on support, you can [book an office hours call](https://memgraph.com/office-hours).

**Comment by katarinasupe** [comment]
And forgot to mention @siddharth-gitrepo, here are the best practices for import in Memgraph: https://memgraph.com/docs/data-migration/best-practices

If you're experiencing issues with these steps, please schedule an office hours call so we can help you out 🙏

**Comment by siddharth-gitrepo** [comment]
Thanks for sharing ! i will try it out. i did try something similar earlier using unwind command, this is with load csv command.
