### ISSUE TITLE
[BUG] CSVLocalFileSystemImporter can't load datetime from csv

### ISSUE THREAD

**Issue by SuperBo** [memgraph/gqlalchemy#300]
**Memgraph version** Which version did you use?
Memgraph v2.13.0

**Environment** Some information about the environment you are using Memgraph
on: operating system, how do you connect, with or without docker, which driver
etc.

Docker

**Describe the bug** 

Cant load datetime string from csv to memgraph.

**To Reproduce** Steps to reproduce the behavior:

Use following scripts
```python
importer = loaders.CSVLocalFileSystemImporter(
    data_configuration=yaml.safe_load(DATA_CONFIG),
    path = "tmp/airflow/data",
    memgraph=memgraph
)
importer.translate(drop_database_on_start=True)
````

**Expected behavior** 

No error

**Logs** If applicable, add logs of Memgraph, CLI output or screenshots to help
explain your problem.

```sh
Loading data from table tmp/airflow/data/a.csv...
Traceback (most recent call last):
  File "/Users/superbo/Workspace/airflow-pipelines/test_memgraph_load.py", line 36, in <module>
    load_data()
  File "/Users/superbo/Workspace/airflow-pipelines/test_memgraph_load.py", line 32, in load_data
    importer.translate(drop_database_on_start=True)
  File "/Users/superbo/Workspace/airflow-pipelines/.venv/lib/python3.11/site-packages/gqlalchemy/transformations/importing/loaders.py", line 472, in translate
    self._load_nodes()
  File "/Users/superbo/Workspace/airflow-pipelines/.venv/lib/python3.11/site-packages/gqlalchemy/transformations/importing/loaders.py", line 480, in _load_nodes
    self._save_row_as_node(label=collection_name, row=row)
  File "/Users/superbo/Workspace/airflow-pipelines/.venv/lib/python3.11/site-packages/gqlalchemy/transformations/importing/loaders.py", line 591, in _save_row_as_node
    QueryBuilder(connection=self._memgraph)
  File "/Users/superbo/Workspace/airflow-pipelines/.venv/lib/python3.11/site-packages/gqlalchemy/query_builders/declarative_base.py", line 748, in node
    properties_str = to_cypher_properties(kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/superbo/Workspace/airflow-pipelines/.venv/lib/python3.11/site-packages/gqlalchemy/utilities.py", line 157, in to_cypher_properties
    value_str = to_cypher_value(value, config)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/superbo/Workspace/airflow-pipelines/.venv/lib/python3.11/site-packages/gqlalchemy/utilities.py", line 109, in to_cypher_value
    return f"{datetimeKwMapping[value_type]}('{_format_timedelta(value) if isinstance(value, timedelta) else value.isoformat()}')"
              ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: <class 'pandas._libs.tslibs.timestamps.Timestamp'>
```

**Additional context** Add any other context about the problem here.

**Comment by matea16** [comment]
Hi @SuperBo, thank you for reporting this. Would you be able to share your `DATA_CONFIG` file in order for us to replicate your issue? You don't have to share real data if it's sensitive, I'm just interested in the format of the file

**Comment by SuperBo** [comment]
@matea16, here is example data, i'm using pyarrow==13.0.0

```
account_id,phone_no,created_dt,updated_dt
abc1,+1212423,2019-08-28 12:19:18,
bcd2,+12123232,2021-06-09 09:05:41,2021-06-09 09:05:41
b11e,+94745734,2021-12-13 16:42:45,2021-12-13 16:42:45
```

**Comment by matea16** [comment]
Thank you for providing the data, we'll take a look at your issue shortly. I'll let you know if we have any additional questions to help us with the debugging :)

**Comment by katarinasupe** [comment]
Hi @SuperBo, I see that you shared your CSV data, but did you create a data configuration object, [similar to the the documentation](https://memgraph.github.io/gqlalchemy/how-to-guides/loaders/import-table-data-to-graph-database/)? If yes, can you share that too?

**Comment by matea16** [comment]
@SuperBo, I believe the issue with your CSV file could be due to the format of your date field. In our docs, you can see supported formats of temporal types, including the [local time format](https://memgraph.com/docs/fundamentals/data-types#localdatetime). Let me know if adjusting that format helps

**Comment by SuperBo** [comment]
Hi @matea16, I also tested with iso datetime format "yyyy-MM-ddThh:mm:ss", and still met the same error.

@katarinasupe : of course, I created a data configuration like this

```yaml
indices:
    accounts:
        - account_id
    transactions:
        - transaction_number

name_mappings:
    accounts:
        label: Account
    transactions:
        label: INTERACT

one_to_many_relations:
    accounts: []
    transactions: []
```

**Comment by SuperBo** [comment]
@matea16, I think this error will happens depends on your dependencies, please test with following dependencies

- python==3.11.5

requirments.txt
```
pyarrow==13.0.0
pandas==2.1.4
GQLAlchemy==1.5.1
```

**Comment by SuperBo** [comment]
hello @matea16 , new update, the problem comes from the remaining file. In that file, I put timestamp format as follwing:

`2024-01-04T03:48:11.336Z`

**Comment by matea16** [comment]
that format is unfortunately not supported since timezones are not supported, does it work without the timezone at the end?

**Comment by SuperBo** [comment]
I removed the last "Z" and the same error still occurs. However, when I remove the microseconds part, it works.

**Comment by katarinasupe** [comment]
I will close this issue since it was related to how Memgraph handles time format.

**Comment by matea16** [comment]
Hi @SuperBo, I'm happy to let you know that zoned datetime data type has been added to Memgraph to the [latest release](https://memgraph.com/docs/release-notes#lab-v2140---may-23-2024) with the following PR: https://github.com/memgraph/memgraph/pull/1866

**Comment by SuperBo** [comment]
Thank you Memgraph team, you rocks 👍

**Comment by katarinasupe** [comment]
Zoned datetime has been added to Memgraph, but in order for it to work properly in GQLAlchemy, I think `datetime` keyword should still be [added to the GQLAlchemy](https://github.com/memgraph/gqlalchemy/blob/main/gqlalchemy/models.py#L35-L39) in order for OGM to work properly.

**Comment by katarinasupe** [comment]
@matea16 I set a new milestone for GQLAlchemy. Will you be able to implement this until July 3rd?

**Comment by matea16** [comment]
Yes, I'll make sure to have it ready by July 3rd
