### ISSUE TITLE
Add tests for validators

### ISSUE THREAD

**Issue by MasterMedo** [memgraph/gqlalchemy#62]
Node, Edge and Path graph objects are derived from Pydantic's `BaseModel`, and the graph properties used in a graph database correspond to Pydantic's `Field` objects which support validators natively. Here is the documentation for Pydantic's field validators: https://pydantic-docs.helpmanual.io/usage/validators/

**Comment by g-despot** [comment]
Added test for pydantic validators. ([PR 89](https://github.com/memgraph/gqlalchemy/pull/89))
