### ISSUE TITLE
Arguments in where method

### ISSUE THREAD

**Issue by katarinasupe** [memgraph/gqlalchemy#74]
The [`where`](https://github.com/memgraph/gqlalchemy/blob/main/gqlalchemy/query_builder.py#L421) method has the argument `property`, which can actually be a variable, because you can use the `WHERE` clause to filter by labels, not only by properties. Maybe rename the argument to a more generic name (item). Also, when using `.where("node", ":", "Stream")`, it automatically creates spaces -> `node : Stream`, and that is not common for Cypher.

Example usage:

```
CALL pagerank.get()
YIELD node, rank
WITH node, rank
WHERE node:Stream OR node:User
RETURN node, rank
ORDER BY rank DESC
LIMIT 50;
```

```
Call("pagerank.get").yield_()
  .with_(
      {"node": "node", "rank": "rank"}
  ).where("node", ":", "Stream")
  .or_where("node", ":", "User")
  .return_({"node": "node", "rank": "rank"})
  .order_by("rank DESC")
  .limit(
      50
)
```

**Comment by MasterMedo** [comment]
There are a lot of inconsistencies regarding white spaces in the query builder. I personally dislike that, but I haven't touched the query builder yet. This is a valid complaint from my perspective.

**Comment by g-despot** [comment]
Here is a link for the [Memgrpah Grammar](https://github.com/memgraph/memgraph/blob/4817be0addcd496266694f60c0bf7f6589e01358/src/query/frontend/opencypher/grammar/Cypher.g4). @brunos252
